# Generated by Django 4.0.6 on 2022-07-19 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fruits',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('fruit_name', models.CharField(max_length=128)),
                ('fruit_description', models.TextField()),
                ('fruit_price', models.FloatField()),
                ('fruit_manufacture_date', models.DateField()),
                ('fruit_is_fresh', models.BooleanField(default=True)),
            ],
        ),
    ]
