# Generated by Django 4.0.6 on 2022-07-19 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parking_lot_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Fruits',
            new_name='Fruit',
        ),
    ]
