# Generated by Django 4.0.6 on 2022-07-19 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking_lot_app', '0003_alter_fruit_options_alter_fruit_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fruit',
            name='fruit_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
