# Generated by Django 4.0.6 on 2022-07-19 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking_lot_app', '0005_alter_fruit_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('in_time', models.DateTimeField()),
                ('out_time', models.DateTimeField(blank=True, null=True)),
                ('vehicle_type', models.CharField(choices=[('2-WHEELER', 'Two Wheeler'), ('4-WHEELER', 'Four Wheeler')], default='2-WHEELER', max_length=9)),
                ('amount', models.FloatField(blank=True, null=True)),
                ('amount_received', models.BooleanField(default=False)),
                ('reference_id', models.CharField(max_length=20, unique=True)),
            ],
            options={
                'verbose_name': 'parking',
                'db_table': 'parking',
                'ordering': ['reference_id'],
                'unique_together': {('reference_id', 'vehicle_type')},
            },
        ),
        migrations.CreateModel(
            name='Slot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('two_wheeler_count', models.IntegerField(default=20)),
                ('four_wheeler_count', models.IntegerField(default=20)),
            ],
        ),
        migrations.DeleteModel(
            name='Fruit',
        ),
    ]
